// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fastRank
IntegerVector fastRank(NumericMatrix pmat, IntegerVector Zs);
RcppExport SEXP _ClassEx_fastRank(SEXP pmatSEXP, SEXP ZsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type pmat(pmatSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Zs(ZsSEXP);
    rcpp_result_gen = Rcpp::wrap(fastRank(pmat, Zs));
    return rcpp_result_gen;
END_RCPP
}
// fastRank1nn
NumericVector fastRank1nn(NumericMatrix Xm, NumericMatrix Ym, IntegerVector Zs);
RcppExport SEXP _ClassEx_fastRank1nn(SEXP XmSEXP, SEXP YmSEXP, SEXP ZsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Xm(XmSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Ym(YmSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Zs(ZsSEXP);
    rcpp_result_gen = Rcpp::wrap(fastRank1nn(Xm, Ym, Zs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ClassEx_fastRank", (DL_FUNC) &_ClassEx_fastRank, 2},
    {"_ClassEx_fastRank1nn", (DL_FUNC) &_ClassEx_fastRank1nn, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_ClassEx(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
