# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Computing the rank of the correct label given classification scores.
#' @param pmat Matrix of margins m_y(x) for test instances, rows are observations and columns are labels.
#' @param Zs True labels.
fastRank <- function(pmat, Zs) {
    .Call('_ClassEx_fastRank', PACKAGE = 'ClassEx', pmat, Zs)
}

#' @title Computing the rank of the Euclidean distance between observation and correct centroid vs all centroids.
#' @param Xm Matrix of centroids, rows are centroids and columns are dimensions.
#' @param Ym Data matrix, rows are observations and columns are dimensions.
#' @param Zs Assignments of observations to centroids.
fastRank1nn <- function(Xm, Ym, Zs) {
    .Call('_ClassEx_fastRank1nn', PACKAGE = 'ClassEx', Xm, Ym, Zs)
}

